apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  selector:
    app: products
  ports:
    - port: 9091
      targetPort: 8080-tcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
      annotations:
        revision: "bab673c5f6b09977a97e7ed919e5d04cd7b749a2"
        buildDate: "20220327201424"
    spec:
      containers:
        - name: products
          image: host.k3d.internal:5000/products:latest
          ports:
            - containerPort: 8080
              name: 8080-tcp
