apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  selector:
    app: products
  ports:
    - port: 9091
      targetPort: 8080-tcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
      annotations:
        revision: "3cfb3241f20d5df7588865731e22491b15f989c3"
        buildDate: "20220405122846"
    spec:
      containers:
        - name: products
          image: host.k3d.internal:5000/products:latest
          ports:
            - containerPort: 8080
              name: 8080-tcp
