apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  name: repo-gitops
  namespace: argocd
type: Opaque
stringData:
  username: tekton
  password: Z2hwX1VWYUZHN1RydTNKclJvNGJYN0J2UnR6WGd3YmNxajFwb0lvMg==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: cicd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://github.com/Manikanta-Reddy-Pasala/tekton-argocd-poc
      passwordSecret:
        name: repo-gitops
        key: password
      usernameSecret:
        name: repo-gitops
        key: username
