apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-to-gitops-repo
  namespace: cicd
spec:
  params:
    - name: url-gitops
    - name: deployments-dir
      description: deployments-dir
    - name: deployment-file
      description: Deployment file
    - name: commit
      description: commit
  steps:
   - name: push-changes-gitops
     image: alpine/git:v2.26.2
     script: |
        #!/bin/sh
        set -e

        git config --global user.email "manikantareddy.pasala@gmail.com"
        git config --global user.name "Manikanta-Reddy-Pasala"

        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDusCFAgYi25ExzqXmaj9dzMG0xUQ9CwSICWGNuOl7eoD4pisXOo5rtPrMjmdckoQllOTkRbp63y5UOKoi6hsFRRDSQ1NmFMWlM+pnIgg3dZyORy65DGyFSs0I64HvynGrfBTJRS1yaTboJSjSYXGzMSeS9/YdHmpqYxYZfiiDiibdzD0Km1J60QiSoyApl2tdMLAKBUS25IRxXOQvzwySc2/yOrGtRS0IE68rQp0Ix2U8woZF0RHpwHRxO64gtZDH2pU5YLS8vvXA86lcJkUYLnrchmX7c+2hQir5oxRWl66Oku7tNxJ+CaB48g4zjKbwvTo37fEFPrDZ2YlxV5p7uMC+JR/m9+/406xqLtvu4QC19bEjoO0yno7T+AXgT7RFR8nDD8vYmwCsGv/47eZ3bdIyMRpYQoEAvQHXAP8E6uUwiLFApz+AMs3A2ovmNn6f6qXiWWpS1ZxwV/mN/DOazhDGJWUWYkcUIn6uwjADMy3jnOWwUUFmLGGE3TRcqHOEDK+R3TAY+XC/oySgDIxxjq9oAAhz8oH+5m6xMGhlMhr3d2k5aGNrVR1Xn+m4MQsh2Edv2TC1s1SLSUcQ2Q99Zw0buYgQRYBUGvN1cEUbz0n1wjIr+ma5XGweErqToqqGvKiM/fRansFVCnaq7jAUMPG6/hIAzKofyqeKvCNMOIw== manikantareddy.pasala@gmail.com" >> ~/.ssh/id_rsa.pub

        cd gitops/$(params.deployments-dir)

        buildDate=$(date '+%Y%m%d%H%M%S')
        sed -i "s#revision: \"[a-zA-Z0-9]\\+\"#revision: \"$(params.commit)\"#" $(params.deployment-file)
        sed -i "s#buildDate: \"[0-9]\\+\"#buildDate: \"$buildDate\"#" $(params.deployment-file)
        cat $(params.deployment-file)

        git add -u
        git commit -m "[tekton] updating deployment"
        git push